name: Sonar base branch

on:
  push:
    branches:
      - 'master'

jobs:
  sonar-base-branch:
    name: Sonar base branch
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: afe7c8b512b087a5cb2a83de8e6f161bcdffcca9
          SONAR_HOST_URL: https://sonarcloud.io
